### ISSUE TITLE
build on ubuntu 14

### ISSUE THREAD

**Issue by scottf-tvw** [rzurad/waveform#3]
gcc47 -I/usr/local/include/ffmpeg -L/usr/local/lib/ffmpeg -I/usr/local/include -L/usr/local/lib -o waveform main.c -Wall -g -O3 -lavcodec -lavutil -lavformat -lpng -lm
make: gcc47: Command not found
make: *** [waveform] Error 127

**Comment by rzurad** [comment]
The current Makefile is pretty useless as it's meant for a specific target machine. One of these days, I need to give this thing a proper Makefile. I have no idea when I'll have the time to do that, unfortunately.

Unless somebody did it for me so I didn't have to. That would also be acceptable :)

**Comment by rzurad** [comment]
https://github.com/rzurad/waveform/issues/4
