### ISSUE TITLE
Should have an -o option for output file

### ISSUE THREAD

**Issue by MaffooBristol** [rzurad/waveform#5]
I was a bit confused and thought that building it hadn't worked when it printed the PNG output to stdout, but then realised I could `>` it into a file. Would be nice to have an `--output` or `-o` option to specify where to send it.

**Comment by rzurad** [comment]
There already is one :)

From the help/README:
```
-o FILE
        Output file for PNG. If -o is omitted, the png will be written
        to stdout.
```

(unless for some reason it's not working. If so, feel free to reopen the ticket)

**Comment by MaffooBristol** [comment]
![image](https://cloud.githubusercontent.com/assets/3296828/6192372/0cca83b2-b3a9-11e4-9d72-3f14c6587957.png)

Um... oh yeah... I didn't see that! I'm just a bit too github issue trigger happy, it seems :P
